### ISSUE TITLE
Is the goal of this repor to find people who don't follow you back ?

### ISSUE THREAD

**Issue by ishandutta2007** [Kiumarsnaderi/Instagram-unfaithful-friend-finder#1]
"unfaithful" term is not clear in this scenario, if they are already following you they are not followers, so what exactly is their unfaithfulness? Or do you intend to find people who have followed you but are not engaging with your posts?

PS: Sorry I didn't get time to deep dive into your code, so thought of resolving doubts over a discussion. 👍

**Comment by Kiumarsnaderi** [comment]
Thanks for your comment. I agree with you therefore changed the repository name :)
It is not much to look into just few lines of code

**Comment by ishandutta2007** [comment]
But I still didn't get the answer, Which of these two does it do ?
I was a question not an advice :)

**Comment by ishandutta2007** [comment]
Ah ok got it, you changed the description not really the name..
